package scripts.com.mercosur.slayer.models.items;

public enum ItemProperty {

	LIGHT_SOURCE, ANTI_POISON, FACE_MASK, BUG_LANTERN, MIRROR_SHIELD, TASK_CONSULTING,
	ICE_COOLER, BAG_OF_SALT, EARMUFFS, SPINY_HELMET, BLACK_MASK, INSULATED_BOOTS, SLAYER_BELL,
	SLAYER_GLOVES, LEAF_BLADE, BROAD, FUNGICIDE, NOSE_PEG, ROCK_HAMMER, ANTI_FIRE
}
